"""Noise-first, error-aware sensing for complex natural scenes."""

from .domain import (
    AuditRecord,
    BBox,
    Candidate,
    ErrorClass,
    InteractionEvent,
    InteractionState,
    SceneState,
    TargetSpec,
)
from .layered_visit_truth import (
    BiologicalTruthAnnotation,
    CouplingTruthAnnotation,
    LayeredTruthJoin,
    NuisanceTruthAnnotation,
    SupportTruthAnnotation,
    join_layered_truth,
)
from .noise import (
    NoiseFirstPolicy,
    NoiseObservation,
    NoiseSource,
    ObservabilityDecision,
    ObservabilityState,
)
from .nuisance_effects import NuisanceEffect, NuisanceProfile, profile_for
from .observation_triad import (
    InferentialStatus,
    NuisanceEvidence,
    ObservationAvailability,
    ObservationInterpretation,
    ObservationSupport,
    ObservationTriadPolicy,
    ProcessPreservingObservationTriadPolicy,
    TargetEvidence,
    TriadState,
)
from .phase_localisation import (
    FROZEN_V14B_GRID,
    FROZEN_V14B_PHASE_SURFACE_SHA256,
    AxisBracket,
    DimensionlessPhaseCoordinate,
    EmpiricalPhaseMeasurements,
    FrozenPhaseGrid,
    GridPosition,
    PhaseGridLocation,
    PhaseMeasurementProvenance,
    compute_phase_coordinate,
    localise_on_frozen_v14b_grid,
)
from .support_estimation import (
    PrimaryStreamSupportEstimate,
    PrimaryStreamSupportEstimator,
    PrimaryStreamSupportMeasurements,
    SupportComponentMeasurement,
    SupportEstimatorValidationSummary,
    SupportMeasurementProvenance,
    evaluate_support_estimates,
)
from .support_measurement import (
    PrimaryStreamMeasurementConfig,
    VisibilityMeasurement,
    measure_primary_stream_support,
)
from .support_truth import (
    PrimaryStreamSupportTruth,
    SupportComponentState,
    SupportTruthResolution,
)
from .target_routes import TargetEvidenceRoute, TargetRouteEvidence
from .visit_annotation import (
    AnnotationBatchSummary,
    RawVisitAnnotation,
    assert_algorithm_fields_absent,
    validate_raw_annotations,
)
from .visit_observation import (
    DiagnosticAction,
    VisitObservationRecord,
    VisitObservationStatus,
    VisitObservationSummary,
    diagnostic_actions,
    summarise_visit_observations,
    visit_record_from_interpretation,
)
from .visit_rate import (
    BlockObservationExposure,
    BlockVisitRate,
    VisitEventDetection,
    VisitRateSummary,
    estimate_block_visit_rates,
)
from .visit_systems import (
    VisitSystemInputs,
    VisitSystemThresholds,
    VisitSystemVariant,
    evaluate_visit_system_variants,
    predict_all_visit_variants,
    predict_visit_variant,
)
from .visit_validation import (
    CoupledResponseResolution,
    VisitPredictionRecord,
    VisitTruthRecord,
    VisitTruthResolution,
    VisitTruthState,
    VisitValidationSummary,
    evaluate_visit_predictions,
    prediction_from_triad,
)

__all__ = [
    "FROZEN_V14B_GRID",
    "FROZEN_V14B_PHASE_SURFACE_SHA256",
    "AnnotationBatchSummary",
    "AuditRecord",
    "AxisBracket",
    "BBox",
    "BiologicalTruthAnnotation",
    "BlockObservationExposure",
    "BlockVisitRate",
    "Candidate",
    "CoupledResponseResolution",
    "CouplingTruthAnnotation",
    "DiagnosticAction",
    "DimensionlessPhaseCoordinate",
    "EmpiricalPhaseMeasurements",
    "ErrorClass",
    "FrozenPhaseGrid",
    "GridPosition",
    "InferentialStatus",
    "InteractionEvent",
    "InteractionState",
    "LayeredTruthJoin",
    "NoiseFirstPolicy",
    "NoiseObservation",
    "NoiseSource",
    "NuisanceEffect",
    "NuisanceEvidence",
    "NuisanceProfile",
    "NuisanceTruthAnnotation",
    "ObservabilityDecision",
    "ObservabilityState",
    "ObservationAvailability",
    "ObservationInterpretation",
    "ObservationSupport",
    "ObservationTriadPolicy",
    "PhaseGridLocation",
    "PhaseMeasurementProvenance",
    "PrimaryStreamMeasurementConfig",
    "PrimaryStreamSupportEstimate",
    "PrimaryStreamSupportEstimator",
    "PrimaryStreamSupportMeasurements",
    "PrimaryStreamSupportTruth",
    "ProcessPreservingObservationTriadPolicy",
    "RawVisitAnnotation",
    "SceneState",
    "SupportComponentMeasurement",
    "SupportComponentState",
    "SupportEstimatorValidationSummary",
    "SupportMeasurementProvenance",
    "SupportTruthAnnotation",
    "SupportTruthResolution",
    "TargetEvidence",
    "TargetEvidenceRoute",
    "TargetRouteEvidence",
    "TargetSpec",
    "TriadState",
    "VisibilityMeasurement",
    "VisitEventDetection",
    "VisitObservationRecord",
    "VisitObservationStatus",
    "VisitObservationSummary",
    "VisitPredictionRecord",
    "VisitRateSummary",
    "VisitSystemInputs",
    "VisitSystemThresholds",
    "VisitSystemVariant",
    "VisitTruthRecord",
    "VisitTruthResolution",
    "VisitTruthState",
    "VisitValidationSummary",
    "assert_algorithm_fields_absent",
    "compute_phase_coordinate",
    "diagnostic_actions",
    "estimate_block_visit_rates",
    "evaluate_support_estimates",
    "evaluate_visit_predictions",
    "evaluate_visit_system_variants",
    "join_layered_truth",
    "localise_on_frozen_v14b_grid",
    "measure_primary_stream_support",
    "predict_all_visit_variants",
    "predict_visit_variant",
    "prediction_from_triad",
    "profile_for",
    "summarise_visit_observations",
    "validate_raw_annotations",
    "visit_record_from_interpretation",
]

__version__ = "0.1.0"
